replicaCount: 1

# image:
#   repository: hub.docker.com/yaleits/minion

# imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: {}
  rules:
    - paths: ['/v1/minion']

probePath: '/v1/minion/ping'
